## Creating a reasoning model using unsloth

This notebook makes use of unsloth to finetune a llama 3.1 model into a reasoning model. I would recommend using the unsloth library compared to just using the huggingface library as it requires less memory and is faster.

Adapted from unsloth notebooks, if something is broken check on:
https://unsloth.ai/

In [1]:
%%capture
import os
!pip install --no-deps unsloth vllm
!pip install --no-deps unsloth vllm
# [NOTE] Do the below ONLY in Colab! Use [[pip install unsloth vllm]]
# Skip restarting message in Colab
import sys, re, requests; modules = list(sys.modules.keys())
for x in modules: sys.modules.pop(x) if "PIL" in x or "google" in x else None
!pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post3 peft trl triton cut_cross_entropy unsloth_zoo
!pip install sentencepiece protobuf datasets huggingface_hub hf_transfer

# vLLM requirements - vLLM breaks Colab due to reinstalling numpy
f = requests.get("https://raw.githubusercontent.com/vllm-project/vllm/refs/heads/main/requirements/common.txt").content
with open("vllm_requirements.txt", "wb") as file:
    file.write(re.sub(rb"(transformers|numpy|xformers)[^\n]{1,}\n", b"", f))
!pip install -r vllm_requirements.txt

### Add lora to base model and patch with Unsloth

In [2]:
# from unsloth import FastLanguageModel
# import torch
# max_seq_length = 1024
# lora_rank = 32

# model, tokenizer = FastLanguageModel.from_pretrained(
#     model_name = "Qwen/Qwen2.5-3B-Instruct",
#     max_seq_length = max_seq_length,
#     load_in_4bit = True,
#     fast_inference = True,
#     max_lora_rank = lora_rank,
#     gpu_memory_utilization = 0.6,
# )

# model = FastLanguageModel.get_peft_model(
#     model,
#     r = lora_rank,
#     target_modules = [
#         "q_proj", "k_proj", "v_proj", "o_proj",
#         "gate_proj", "up_proj", "down_proj",
#     ],
#     lora_alpha = lora_rank,
#     use_gradient_checkpointing = "unsloth",
#     random_state = 3407,
# )

# ---- hard-disable vLLM path + import order ----
# Disable vLLM to avoid cudagraph FULL issues on T4
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1"   # or: os.environ["UNSLOTH_FORCE_NO_VLLM"] = "1"

import unsloth
from unsloth import FastLanguageModel
import torch

torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True

max_seq_length = 1024
lora_rank = 32
FORCE_GPU = {"": "cuda:0"}  # keep everything on GPU for 4-bit

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name              = "Qwen/Qwen2.5-3B-Instruct",
    max_seq_length          = max_seq_length,
    load_in_4bit            = True,
    fast_inference          = False,          # no vLLM
    max_lora_rank           = lora_rank,
    gpu_memory_utilization  = 0.6,
    device_map              = FORCE_GPU,      # avoid CPU/disk offload
    low_cpu_mem_usage       = True,
    torch_dtype             = torch.float16,  # explicit dtype
)

model = FastLanguageModel.get_peft_model(
    model,
    r                          = lora_rank,
    target_modules             = ["q_proj","k_proj","v_proj","o_proj",
                                  "gate_proj","up_proj","down_proj"],
    lora_alpha                 = lora_rank,
    use_gradient_checkpointing = "unsloth",
    random_state               = 3407,
)

print("Model ready ✅ on", next(model.parameters()).device)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 09-27 06:16:01 [__init__.py:216] Automatically detected platform cuda.
ERROR 09-27 06:16:02 [fa_utils.py:57] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8

WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.6.0+cu124 with CUDA 1204 (you have 2.8.0+cu126)
    Python  3.12.9 (you have 3.12.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

========
Switching to PyTorch attention since your Xformers is broken.
========

Unsloth: Xformers was not installed correctly.
Please install xformers separately first.
Then confirm if it's correctly installed by running:
python -m xformers.info

Longer error message:
xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.6.0+cu124 with CUDA 1204 (you have 2.8.0+cu126)
    Python  3.12.9 (you have 3.12.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.9.9: Fast Qwen2 patching. Transformers: 4.56.1. vLLM: 0.10.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.4.0
\        /    Bfloat16 = FALSE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.36G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

Unsloth 2025.9.9 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

Model ready ✅ on cuda:0

### Data Prep
<a name="Data"></a>

Uses [@willccbb](https://gist.github.com/willccbb/4676755236bb08cab5f4e54a0475d6fb) reward functions.

In [3]:
import re
from datasets import load_dataset, Dataset

# Load and prep dataset
SYSTEM_PROMPT = """
Respond in the following format:
<reasoning>
...
</reasoning>
<answer>
...
</answer>
"""

XML_COT_FORMAT = """\
<reasoning>
{reasoning}
</reasoning>
<answer>
{answer}
</answer>
"""

def extract_xml_answer(text: str) -> str:
    answer = text.split("<answer>")[-1]
    answer = answer.split("</answer>")[0]
    return answer.strip()

def extract_hash_answer(text: str) -> str | None:
    if "####" not in text:
        return None
    return text.split("####")[1].strip()

# uncomment middle messages for 1-shot prompting
def get_gsm8k_questions(split = "train") -> Dataset:
    data = load_dataset('openai/gsm8k', 'main')[split] # type: ignore
    data = data.map(lambda x: { # type: ignore
        'prompt': [
            {'role': 'system', 'content': SYSTEM_PROMPT},
            {'role': 'user', 'content': x['question']}
        ],
        'answer': extract_hash_answer(x['answer'])
    }) # type: ignore
    return data # type: ignore

dataset = get_gsm8k_questions()

# Reward functions
def correctness_reward_func(prompts, completions, answer, **kwargs) -> list[float]:
    responses = [completion[0]['content'] for completion in completions]
    q = prompts[0][-1]['content']
    extracted_responses = [extract_xml_answer(r) for r in responses]
    print('-'*20, f"Question:\n{q}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}")
    return [2.0 if r == a else 0.0 for r, a in zip(extracted_responses, answer)]

def int_reward_func(completions, **kwargs) -> list[float]:
    responses = [completion[0]['content'] for completion in completions]
    extracted_responses = [extract_xml_answer(r) for r in responses]
    return [0.5 if r.isdigit() else 0.0 for r in extracted_responses]

def strict_format_reward_func(completions, **kwargs) -> list[float]:
    """Reward function that checks if the completion has a specific format."""
    pattern = r"^<reasoning>\n.*?\n</reasoning>\n<answer>\n.*?\n</answer>\n$"
    responses = [completion[0]["content"] for completion in completions]
    matches = [re.match(pattern, r) for r in responses]
    return [0.5 if match else 0.0 for match in matches]

def soft_format_reward_func(completions, **kwargs) -> list[float]:
    """Reward function that checks if the completion has a specific format."""
    pattern = r"<reasoning>.*?</reasoning>\s*<answer>.*?</answer>"
    responses = [completion[0]["content"] for completion in completions]
    matches = [re.match(pattern, r) for r in responses]
    return [0.5 if match else 0.0 for match in matches]

def count_xml(text) -> float:
    count = 0.0
    if text.count("<reasoning>\n") == 1:
        count += 0.125
    if text.count("\n</reasoning>\n") == 1:
        count += 0.125
    if text.count("\n<answer>\n") == 1:
        count += 0.125
        count -= len(text.split("\n</answer>\n")[-1])*0.001
    if text.count("\n</answer>") == 1:
        count += 0.125
        count -= (len(text.split("\n</answer>")[-1]) - 1)*0.001
    return count

def xmlcount_reward_func(completions, **kwargs) -> list[float]:
    contents = [completion[0]["content"] for completion in completions]
    return [count_xml(c) for c in contents]

README.md: 0.00B [00:00, ?B/s]

main/train-00000-of-00001.parquet:   0%|          | 0.00/2.31M [00:00<?, ?B/s]

main/test-00000-of-00001.parquet:   0%|          | 0.00/419k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!

In [5]:
max_prompt_length = 256

from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    learning_rate = 5e-6,
    adam_beta1 = 0.9,
    adam_beta2 = 0.99,
    weight_decay = 0.1,
    warmup_ratio = 0.1,
    lr_scheduler_type = "cosine",
    optim = "paged_adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1,
    num_generations = 6,
    max_prompt_length = max_prompt_length,
    max_completion_length = max_seq_length - max_prompt_length,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 100,
    save_steps = 100,
    max_grad_norm = 0.1,
    report_to = "none",
    output_dir = "outputs",
)

Unsloth: We now expect `per_device_train_batch_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 6

In [6]:
trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        xmlcount_reward_func,
        soft_format_reward_func,
        strict_format_reward_func,
        int_reward_func,
        correctness_reward_func,
    ],
    args = training_args,
    train_dataset = dataset,
)
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 7,473 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 6 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (6 x 1 x 1) = 6
 "-____-"     Trainable parameters = 59,867,136 of 3,145,805,824 (1.90% trained)

-------------------- Question:
A concert ticket costs $40. Mr. Benson bought 12 tickets and received a 5% discount for every ticket bought that exceeds 10. How much did Mr. Benson pay in all?
Answer:
476
Response:
<reasoning>
Mr. Benson bought 12 concert tickets, so 2 of the tickets were eligible for a 5% discount because he bought more than 10 tickets. The cost of a ticket is $40. The first 10 tickets cost $40 each, and the 12th ticket gets a 5% discount.

Calculate the cost for the first 10 tickets:
10 tickets * $40 per ticket = $400

Next, calculate the discounted price for the 12th ticket:
Original price = $40
Discount = 5% of $40 = 0.05 * 40 = $2
Discounted price = $40 - $2 = $38

Now add the cost of the first 10 tickets with the discounted price of the 12th ticket:
Total cost = $400 + $38 = $438

</reasoning>
<answer>
Mr. Benson paid a total of $438 for the 12 concert tickets.</answer>

Extracted:
Mr. Benson paid a total of $438 for the 12 concert tickets.

Unsloth: Will smartly offload gradients to save VRAM!
-------------------- Question:
Jane is trying to decide whether to buy a house or a trailer. A house costs $480,000 and a trailer costs $120,000. Each loan will be paid in monthly installments over 20 years. How much more is the monthly payment on the house compared to the trailer?
Answer:
1500
Response:
<reasoning>
First, let determine the monthly payments for both loan scenarios (house and trailer) by using the formula for calculating monthly payments on a fixed-rate loan over a period of time. The formula is:

\[ \text{Monthly Payment} = \frac{P \times r \times (1 + r)^n}{(1 + r)^n - 1} \]

Where:
- \( P \) is the principal (loan amount).
- \( r \) is the monthly interest rate.
- \( n \) is the number of payments (loan term in months).

Since the interest rate is not given, we'll assume a standard situation where the monthly payments are made straight into a sinking fund for the house and a down payment for the trailer; simplifying to determine the cost per month for each option.

The cost per month for the house (480,000) and the trailer (120,000) can be assessed by simple annualization (12 months in a year) and then comparing the total yearly costs and subsequently dividing by the number of years to get the monthly cost.

Given:
- Cost of the house = $480,000
- Cost of the trailer = $120,000
- Payment period = 20 years (20 \* 12 = 240 months)

For simplicity, let's assume an annual interest rate and adjust the payments for the trailer, but since the precise monthly interest rate is not given, we'll directly compare the costs as yearly payments:

1. Annual cost for the house:
   \[ \text{Annual House Cost} = \frac{\text{House Cost}}{20 \text{ years}} = \frac{480,000}{20} = $24,000 \]

2. Annual cost for the trailer:
   \[ \text{Annual Trailer Cost} = \frac{\text{Trailer Cost}}{20 \text{ years}} = \frac{120,000}{20} = $6,000 \]

   Since trailer cost is much lower than the house cost per year, we can reasonably assume that the trailer's monthly cost will be significantly less than the house's.

3. Cost per month for the house:
   \[ \text{Monthly House Cost} = \frac{480,000}{240} = $2,000 \]

4. Cost per month for the trailer:
   \[ \text{Monthly Trailer Cost} = \frac{120,000}{240} = $500 \]

Now, a direct comparison of the monthly payments:
\[ \text{Monthly House Cost} - \text{Monthly Trailer Cost} = 2,000 - 500 = $1,500 \]

</reasoning>
<answer>
The monthly payment on the house is $1,500 more than the monthly payment on the trailer.
</answer>
Extracted:
The monthly payment on the house is $1,500 more than the monthly payment on the trailer.
-------------------- Question:
Janet pays $40/hour for 3 hours per week of clarinet lessons and $28/hour for 5 hours a week of piano lessons. How much more does she spend on piano lessons than clarinet lessons in a year?
Answer:
1040
Response:
<reasoning>
To find out how much more Janet spends on piano lessons than on clarinet lessons in a year, we need to calculate the total cost for each and then find the difference.

For clarinet lessons:
Janet pays $40/hour and takes 3 hours per week of clarinet lessons.
The weekly cost for clarinet lessons is \(40 \times 3 = 120\) dollars.
There are 52 weeks in a year, so the yearly cost for clarinet lessons is \(120 \times 52 = 6240\) dollars.

For piano lessons:
Janet pays $28 for each hour and takes 5 hours of lessons per week.
The weekly cost for piano lessons is \(28 \times 5 = 140\) dollars.
The yearly cost for piano lessons is \(140 \times 52 = 7280\) dollars.

Now we need to find the difference between the yearly cost for piano and clarinet lessons:
\(7280 - 6240 = 1040\) dollars.

Thus, Janet spends $1040 more on piano lessons than on clarinet lessons in a year.
</reasoning>
<answer>
1040 dollars
</answer>
Extracted:
1040 dollars
-------------------- Question:
Sabrina is collecting herbs to make a poultice for her grandmother. She needs twice as many basil leaves as sage leaves and 5 fewer sage leaves than verbena leaves. If she needs 12 basil leaves, how many leaves total does she need?
Answer:
29
Response:
<reasoning>
To determine the total number of leaves Sabrina needs, we first figure out the number of each type of herb she needs based on the given relationships and the given basil leaves.

Given she needs 12 basil leaves, and she needs twice as many basil leaves as sage leaves, we can use the information to find the number of sage leaves.
\[ \text{Sage leaves} = \frac{\text{Basil leaves}}{2} = \frac{12}{2} = 6 \]

Next, we calculate the number of verbena leaves. She needs 5 fewer sage leaves than verbena leaves, meaning if we let the number of verbena leaves be \( V \), then:
\[ \text{Sage leaves} = \text{Verbena leaves} - 5 \]
\[ 6 = V - 5 \Rightarrow V = 11 \]

So, she needs 6 sage leaves and 11 verbena leaves. Now we sum these amounts to find the total number of leaves:
\[ \text{Total leaves} = \text{Basil leaves} + \text{Sage leaves} + \text{Verbena leaves} \]
\[ \text{Total leaves} = 12 + 6 + 11 \]
\[ \text{Total leaves} = 29 \]

</reasoning>
<answer>
Sara needs a total of 29 leaves. </answer>
Extracted:
Sara needs a total of 29 leaves.
-------------------- Question:
Over the past five years, on July 4th, the high temperature for Washington, DC has been: 90 degrees in 2020, 90 degrees in 2019, 90 degrees in 2018, 79 degrees in 2017 and 71 degrees in 2016. What is the average temperature for July 4th in Washington, DC over the past 5 years?
Answer:
84
Response:
<reasoning>
To find the average temperature for July 4th in Washington, DC over the past five years, we need to add up all the high temperatures recorded from 2016 to 2020 and then divide by the number of years (5).

Temperatures recorded:
- 2020: 90 degrees
- 2019: 90 degrees
- 2018: 90 degrees
- 2017: 79 degrees
- 2016: 71 degrees

Sum of the temperatures:
90 + 90 + 90 + 79 + 71 = 410 degrees

Average temperature is calculated by dividing the total sum by the number of years:
410 / 5 = 82 degrees

</reasoning>
<answer>
The average temperature for July 4th in Washington, DC over the past five years is 82 degrees.
</answer>
Extracted:
The average temperature for July 4th in Washington, DC over the past five years is 82 degrees.
-------------------- Question:
Rene can finish reading 30 pages in 60 minutes. Lulu can read 27 pages in 60 minutes and Cherry can read 25 pages in 60 minutes. If they have been reading for 240 minutes now, how many pages have they finished reading in total?
Answer:
328
Response:
<reasoning>
To determine the total number of pages read by Rene, Lulu, and Cherry, we need to calculate how many pages each of them can read per minute, and then use that information to find out how many pages each of them has read in 240 minutes.

We know that:
- Rene reads 30 pages in 60 minutes, so she reads \( \frac{30}{60} = \frac{1}{2} \) pages per minute.
- Lulu reads 27 pages in 60 minutes, so she reads \( \frac{27}{60} = \frac{9}{20} \) pages per minute.
- Cherry reads 25 pages in 60 minutes, so she reads \( \frac{25}{60} = \frac{5}{12} \) pages per minute.

Now, let's find out how many pages each of them has read in 240 minutes:
- Rene reads \( \frac{1}{2} \times 240 = 120 \) pages.
- Lulu reads \( \frac{9}{20} \times 240 = 108 \) pages.
- Cherry reads \( \frac{5}{12} \times 240 = 100 \) pages.

So, the total number of pages they have read is the sum of the pages read by Rene, Lulu, and Cherry.

</reasoning>
<answer>
Rene, Lulu, and Cherry have finished reading a total of 120 + 108 + 100 = 328 pages.
</answer>
Extracted:
Rene, Lulu, and Cherry have finished reading a total of 120 + 108 + 100 = 328 pages.
-------------------- Question:
Martin rings the small bell 4 times more than 1/3 as often as the big bell. If he rings both of them a combined total of 52 times, how many times does he ring the big bell?
Answer:
36
Response:
<reasoning>
Let \( x \) be the number of times Martin rings the big bell. Given that Martin rings the small bell 4 times more than 1/3 as often as the big bell, the number of times he rings the small bell can be expressed as \( \frac{1}{3}x + 4 \). The combined total number of times he rings the small and big bell is given as 滔2. So, we can write the equation:

\[ x + (\frac{1}{3}x + 4) = 52 \]

Simplifying the equation to find the value of \( x \):

\[ x + \frac{1}{3}x + 4 = 52 \]
\[ \frac{3}{3}x + \frac{1}{3}x + 4 = 52 \]
\[ \frac{4}{3}x + 4 = 52 \]
\[ \frac{4}{3}x = 52 - 4 \]
\[ \frac{4}{3}x = 48 \]

To isolate \( x \), multiply both sides of the equation by the reciprocal of \(\frac{4}{3}\), which is \(\frac{3}{4}\):

\[ x = 48 \times \frac{3}{4} \]
\[ x = 36 \]

Thus, Martin rings the big bell 36 times.
</reasoning>

<answer>
Martin rings the big bell 36 times.
</answer>
Extracted:
Martin rings the big bell 36 times.
-------------------- Question:
Bert fills out the daily crossword puzzle in the newspaper every day. He uses up a pencil to fill out the puzzles every two weeks. On average, it takes him 1050 words to use up a pencil. How many words are in each crossword puzzle on average?
Answer:
75
Response:
<reasoning>
To solve this problem, we need to determine the average number of words in Bert's crossword puzzles. Given that it takes him 1050 words to use up a pencil, which he uses every two weeks, we can infer that the total number of words from all his crossword puzzles over two weeks is 1050.

Since we know Bert uses up a new pencil every two weeks, we can conclude that the total number of words from the crosswords he does in two weeks is 1050 words. The number of words in each crossword puzzle is the same as the words used on average within a two-week period.

Thus, the average number of words in each crossword puzzle is 1050 words.

Now, to find out how many words are in each crossword puzzle on average, we divide the total words by the number of puzzles Bert completes, which ought to be the same number of puzzles he completes in two weeks.

Without considering the actual number of puzzles but considering the problem constraints, the answer would simply be 1050 words.

Let's verify the logic by assuming Bert completes one puzzle daily. Since he uses up a pencil every two weeks, and two weeks contain 14 days, Bert completes 14 puzzles in two weeks. So, the total number of words in those puzzles is 1050 words. Therefore, the number of words in each puzzle would be:

\[ \frac{1050}{14} \]

However, the problem does not require us to know the  exact number of puzzles, and the central point is that Bert uses 1050 words on average every two weeks.

However, if we assume Bert completes 14 puzzles in two weeks, the average number of words per puzzle is:

\[ \frac{1050}{14} = 75 \]

So, the average number of words per crossword puzzle is 75 words.
...
<answer>
The average number of words in each crossword puzzle is 75 words. </answer>
Extracted:
The average number of words in each crossword puzzle is 75 words.
-------------------- Question:
Matt can make a batch of a dozen cookies using 2 pounds of flour.  He uses 4 bags of flour each weighing 5 pounds.  If Jim eats 15 cookies how many cookies are left?
Answer:
105
Response:
<reasoning>
First, let's determine the amount of flour Matt has. Since he has 4 bags of flour and each bag weighs 5 pounds, the total amount of flour he has is:
\[ 4 \times 5 \text{ pounds} = 20 \text{ pounds} \]

Next, we note that Matt can make a batch of a dozen (12) cookies using 2 pounds of flour. Thus, the total number of batches he can make is:
\[ \frac{20 \text{ pounds}}{2 \text{ pounds per batch}} = 10 \text{ batches} \]

Each batch makes 12 cookies, so the total number of cookies Matt makes is:
\[ 10 \text{ batches} \times 12 \text{ cookies per batch } = 120 \text{ cookies} \]

Jim eats 15 cookies. Thus, the remaining number of cookies is:
\[ 120 \text{ cookies} - 15 \text{ cookies} = 105 \text{ cookies} \]

</reasoning>

<answer>
The remaining number of cookies is 105.
</answer>
Extracted:
The remaining number of cookies is 105.
-------------------- Question:
James decides to build a tin house by collecting 500 tins in a week. On the first day, he collects 50 tins. On the second day, he manages to collect 3 times that number. On the third day, he collects 50 tins fewer than the number he collected on the second day. If he collects an equal number of tins on the remaining days of the week, what's the number of tins he collected each day for the rest of the week?
Answer:
50
Response:
<reasoning>
To determine the number of tins James collects each day for the rest of the week, we need to follow these steps:

1. Find out how many tins James has collected by the third day.
2. Deduct that amount from 500 to find out how many tins he needs to collect from the fourth day till the end of the week.
3. Divide the remaining tins by the number of days left in the week, which is 4 days.

On the first day, James collects 50 tins. On the second day, he collects 3 * 50 = 150 tins. By the third day, he collects 150 - 50 = 100 tins. In total, from the first three days, he has collected 50 + 150 + 10噙 tins.

Subtracting what he has accumulated by the third day from his goal of 500 tin:
500 - (50 + 150 + 100) = 200 tins remaining.

There are 4 days left in the week, so he needs to collect 200 tins over 4 days. To find the number of tins he must collect each day for the rest of the week, we need to divide the remaining tins by the number of remaining days.

\[
\frac{200 \text{ tins}}{4 \text{ days}} = 50 \text{ tins per day}
\]

</reasoning>
<answer>
James collected 50 tins each day for the rest of the week.
</answer>
Extracted:
James collected 50 tins each day for the rest of the week.
-------------------- Question:
A jar of jellybeans has 14 blue jellybeans, 26 purple jellybeans and 40 orange jellybeans. If there are 200 jellybeans in the jar, how many are there of the red color?
Answer:
120
Response:
<reasoning>
To solve this problem, we need to first determine the total number of jellybeans that are not red, then subtract this number from the total number of jellybeans to find the number of red jellybeans.

The total number of jellybeans in the jar is given as 200. We need to find out how many jellybeans are of blue, purple, and orange colors:
- The number of blue jellybeans is 14.
- The number of purple jellybeans is 26.
- The number of orange jellybeans is 40.

Adding the non-red jellybeans together gives:
\[ 14 + 26 + 40 = 80 \]

Now, we subtract this number of non-red jellybeans from the total number of jellybeans, which is 200:
\[ 200 - 80 = 120 \]

Thus, there are 120 red jellybeans in the jar.
</reasoning>
<answer>
120
</answer>
Extracted:
120
-------------------- Question:
Five adults and two children go to see a movie and buy $12 worth of concessions. The total cost of their trip is $76. If each child's ticket is $7, how much, in dollars, are the adult tickets?
Answer:
10
Response:
<reasoning>
To find out the cost of the adult tickets, we first need to determine the total cost of the children's tickets. Since each child's ticket is $7, and there are two children, we can calculate the total cost for the children's tickets as \(2 \times 7 = $14\).

The total cost of movie tickets and concessions is $76. This includes the cost of the movie tickets and the $12 worth of concessions. Therefore, the total cost of movie tickets alone is $76 - $12 = $64.

Since there are five adults, let's denote the price of each adult ticket as \(a\). So, the equation for the total cost of the adult tickets would be \(5a\).

Setting up the equation:
\[
5a = 64
\]

Solving for \(a\):
\[
a = \frac{64}{5} = 12.8
\]

So, the cost of each adult ticket is $12.80.
</reasoning>
<answer>
Each adult ticket costs $12.80.
</answer>
Extracted:
Each adult ticket costs $12.80.
-------------------- Question:
Janelle had 26 green marbles. Then she bought 6 bags of blue marbles. There were 10 marbles in each bag.  She created a gift of 6 green marbles and 8 blue marbles and gave it to a friend. How many marbles does Janelle have now?
Answer:
72
Response:
<reasoning>
Let's break down the problem step byml. Initially, Janelle had 26 green marbles.

Janelle bought 6 bags of blue marbles, with each bag containing 10 blue marbles. Therefore, the total number of blue marbles she bought is calculated as follows:
\[ 6 \text{ bags} \times 10 \text{ marbles per bag} = 60 \text{ blue marbles}. \]

After receiving the gift, she gave away 6 green marbles and 8 blue marbles. Before giving the gift, let's calculate the total marbles she had:
\[ \text{Total green marbles before gift} = 26 + 6 = 32 \text{ green marbles} (\text{from the original 26 green marbles and the 6 green marbles from the gift}). \]
\[ \text{Total blue marbles before gift} = 60 + 8 = 68 \text{ blue marbles} (\text{ from the original 60 blue marbles and the 8 blue marbles from the gift}). \]

Finally, the total number of marbles Janelle has now is the sum of green and blue marbles:
\[ 32 \text{ (green)} + 68 \text{ (blue)} = 100 \text{ total marbles}. \]
</reasoning>
<answer>
Janelle has 100 marbles now.
</answer>
Extracted:
Janelle has 100 marbles now.
-------------------- Question:
Every day in a week, Siena bookmarks 30 website pages from the research she does on her browser. If Siena has 400 bookmarked pages on her bookmarks library now, how many pages will she have in her bookmarks library at the end of March?
Answer:
1330
Response:
<reasoning>
To determine how many pages Siena will have in her bookmarks library at the end of March, we need to:
1. Calculate the number of days from the start of March until the end of March.
2. Multiply the daily bookmarking rate by the number of days from the start to the end of March.
3. Add these new pages to the 400 pages she already has.

Given:
- Siena bookmarks 30 pages per day.
- March has 31 days.
- Currently, she has 400 pages in the library.

Since she bookmarks daily, the number of new pages she will add from the start until the end of March is \(30 \text{ pages/day} \times 31 \text{ days}\). Adding this new count to 400 pages will give the total number of pages at the end of March.

</reasoning>
<answer>
1. Calculate the number of new pages added:
\[ 30 \text{ pages/day} \times 31 \text{ days} = 930 \text{ pages} \]

2. Add the new pages to the existing 400 pages:
\[ 400 \text{ pages} + 930 \text{ pages} = 1330 \text{ pages} \]

Therefore, at the end of March, Siena will have 1330 pages in her bookmarks library.
</answer>
Extracted:
1. Calculate the number of new pages added:
\[ 30 \text{ pages/day} \times 31 \text{ days} = 930 \text{ pages} \]

2. Add the new pages to the existing 400 pages:
\[ 400 \text{ pages} + 930 \text{ pages} = 1330 \text{ pages} \]

Therefore, at the end of March, Siena will have 1330 pages in her bookmarks library.
-------------------- Question:
An old pirate wants to leave his treasure on an island. He has 3500 gold coins. He wants to spread this equally across 5 chests. Additionally, he will put a total of 500 silver coins and twice as many bronze coins as silver, all distributed equally across the chests. How many coins in total will be in each chest?
Answer:
1000
Response:
<reasoning>
First, we calculate the total number of bronze coins. The pirate has twice as many bronze coins as silvers, and he has 500 silver coins. So, the number of bronze coins is 2 * 500 = 1000.

Next, we calculate the total number of coins the pirate wants to distribute. This includes 3500 gold coins, 500 silver coins, and 1000 bronze coins. Therefore, the total number of coins is:
\[ 3500 + 500 + 1000 = 5000. \]

The pirate wants to divide these 5000 coins equally among 5 chests. So, we divide the total number of coins by 5:
\[ \frac{5000}{5} = 1000. \]

This means each chest will have a total of 1000 coins.
</reasoning>
<answer>
Each chest will contain 1000 coins. </answer>
Extracted:
Each chest will contain 1000 coins.
-------------------- Question:

-------------------- Question:
Matthew, the baker, arrives at work early every morning to make his famous caramel-apple coffee cakes for the day.  It usually takes Matthew 1 hour to assemble ingredients, 1.5 hours to bake the cakes, and another 1 hour to decorate each cake with cinnamon sprinkles.  One day, Matthew's oven failed to reach the correct temperature and it took twice as long for the cakes to bake as they usually take.  On that day, how long did it take, in hours, for Matthew to make his famous caramel-apple coffee cakes?
Answer:
5
Response:
<reasoning>
Matthew's usual times for each process are:
- 1 hour to assemble ingredients,
- 1.5 hours to bake (twice as long so 3 hours),
- 1 hour to decorate.

If the oven failed and the baking took twice as long, that means he spent 3 * 2 = 6 hours baking the cakes. On this day, Matthew's total time to make the cake would be the sum of the time to assemble the ingredients, the actual time to bake the cakes, and the time to decorate.

The total time for each process on this day would be:
- Assembling ingredients: 1 hour,
- Baking cakes: 6 hours,
- Decorating: 1 hour.

Adding all these together, the total time taken is 1 + 6 + 1 = 8 hours.
</reasoning>
<answer>
On the day when Matthew's oven failed, it took him 8 hours to make his famous caramel-apple coffee cakes.
</answer>
Extracted:
On the day when Matthew's oven failed, it took him 8 hours to make his famous caramel-apple coffee cakes.
-------------------- Question:
Fran's school just instituted a school uniform policy. Each student needs to buy five complete uniforms, each consisting of pants, shirt, tie and socks. The pants cost $20, the shirt costs twice as much as the pants, the tie costs 1/5 as much as the shirt and the socks cost $3/pair. How many dollars will each student need to spend?
Answer:
355
Response:
<reasoning>
To find out how much each student needs to spend, we first calculate the cost of one complete uniform. The complete uniform consists of pants, shirt, tie, and socks.

1. **Cost of the pants:**
   - Cost of pants: $20.

2. **Cost of the shirt:**
   - The shirt costs twice as much as the pants:
   - Cost of shirt: \(2 \times 20 = 40\) dollars.

3. **Cost of the tie:**
   - The tie costs 1/5 as much as the shirt:
   - Cost of tie: \( \frac{1}{5} \times 40 = 8\) dollars.

4. **Cost of the socks:**
   - Cost of socks: $3.

Next, we add the costs of the components to get the total cost of one complete uniform:
\[ \text{Total cost of one uniform} = 20 + 40 + 8 + 3 = 71 \text{ dollars}. \]

For five complete uniforms:
\[ \text{Total cost for five uniforms} = 5 \times 71 = 355 \text{ dollars}. \]

Therefore, each student will need to spend 355 dollars.
</reasoning>

<answer>
355
</answer>
Extracted:
355
-------------------- Question:
Haman’s father has an egg business supplying the local market. On a Wednesday morning, his father sends him to go and collect 10 trays of eggs for sale from their store. While loading the eggs into the car, he accidentally drops two trays. He calls his father telling him this, and is told to add 7 more trays for sale. How many eggs were sold that day?
Answer:
540
Response:
<reasoning>
Initially, Haman was supposed to collect 10 trays. However, he accidentally dropped 2 trays and 7 more trays were added. We need to determine the total number of trays he ended up with and, assuming each tray contains the same number of eggs (which is not specified, but we can assume it to be a standard number such as 30 or 40 for simplicity if needed) we calculate the number of eggs sold that day.

First, we need to calculate the total number of trays Haman ended up with:

\[ \text{Total trays} = \text{Tried to collect} + \text{Trays dropped} + \text{Trays added} \]
\[ \text{Total trays} = 10 - 2 + 7 = 15 \]

Now, assuming each tray contains 30 eggs (a common egg tray size):

\[ \text{Total eggs} = \text{Total trays} \times \text{Eggs per tray} \]
\[ \text{Total eggs} = 15 \times 30 \]
\[ \text{Total eggs} = 450 \]

Given he was supposed to sell all collected trays, and dropped trays and added more, the total number of trays Haman ended up with is 15 trays, so that would also be the number of trays sold, which equals 450 eggs.
...
<answer>
Haman sold 450 eggs that day.
</answer>
Extracted:
Haman sold 450 eggs that day.
-------------------- Question:
Kaiden is collecting cans of soup for the local soup kitchen. He collects 158 cans during his first week and 259 during the second week. If his goal is to collect 500 cans how many more cans of soup does he need to collect?
Answer:
83
Response:
<reasoning>
Kaiden's total cans collected so far is the sum of the cans collected in the first and second weeks. Therefore, he has collected a total of 158 + 259 cans. His goal is 500 cans. The number of additional cans he needs to reach his goal can be calculated by subtracting the total cans collected (so far) from his goal (500 cans). Thus the final count of additional cans he needs to collect can be found from the calculation: 500 - (158 + 259).
</reasoning>
<answer>
Kaiden needs to collect 183 more cans of soup to reach his goal of 500 cans.
</answer>
Extracted:
Kaiden needs to collect 183 more cans of soup to reach his goal of 500 cans.
-------------------- Question:
Calvin has been saving his hair clippings after each haircut to make a wig for his dog. He has gotten 8 haircuts and knows that he needs 2 more to reach his goal. What percentage towards his goal is he?
Answer:
80
Response:
<reasoning>
To determine what percentage towards his goal Calvin has reached, we first need to calculate the total number of haircuts he aims to do. We know he has already gotten 8 haircuts and needs 2 more to reach his goal. So, the total number of haircuts in his goal is 8 + 2 = 10 haircuts.

Next, we need to determine what fraction of his goal Calvin has achieved so far. He has gotten 8 haircuts out of 10, so the fraction is 8/10, which simplifies to 4/5. To find the percentage, we convert the fraction 4/5 to a percentage by multiplying it by 100.

\[
\text{Percentage achieved} = \frac{4}{5} \times 100 = 80\%
\]

</reasoning>
<answer>
Calvin is 80% towards his goal.
</answer>
Extracted:
Calvin is 80% towards his goal.
-------------------- Question:
Jenny is trying to convince her cat to walk on a leash. The cat spends twenty minutes resisting. Then Jenny coaxes the cat to walk 64 feet at a rate of 8 feet/minute. How many minutes does this whole process take?
Answer:
28
Response:
<reasoning>
Jenny’s cat spends 20 minutes resisting the leash attempt. The cat then walks 64 feet under Jenny's coaxing. Since the cat walks at a rate of 8 feet per minute, we can calculate the time it takes to walk 64 feet.

First, we can find out how many minutes the cat takes to walk 64 feet by dividing the total distance walked by the walking rate:
\[ \text{Time taken to walk 64 feet} = \frac{64 \text{ feet}}{8 \text{ feet/minute}} = 8 \text{ minutes} \]

Next, we add the time for resisting to the time taken to walk 64 feet to find the total process time:
\[ \text{Total process time} = 20 \text{ minutes} + 8 \text{ minutes} = 28 \text{ minutes} \]

</reasoning>
<answer>
28 minutes
</answer>
Extracted:
28 minutes
-------------------- Question:
All 20 of Grant’s baby teeth have fallen out and he has a total of $54 from the tooth fairy. Every time he lost a tooth, he put it under his pillow for the tooth fairy, except for one that he dropped on the way home from school and another he swallowed accidentally. The tooth fairy left Grant $20 when he lost his first tooth. How much did the tooth fairy leave him per tooth after his first tooth, assuming equal money exchanged for each tooth thereafter?
Answer:
2
Response:
<reasoning>
Given that 20 teeth were eventually rewarded by the tooth fairy, but only 18 teeth were placed under the pillow, one was dropped off and another was swallowed. This means that of the initial 20 teeth, 18 were exchanged with the tooth fairy. The total amount exchanged was $54, and $20 was given for the first tooth. Therefore, the amount exchanged after the first tooth was $54 - $20 = $34. To find the amount the tooth fairy left per tooth exchanged from the second tooth onward, divide $34 by the 17 teeth (20 total teeth - 1 tooth dropped - 1 swallowed):

\[ \text{Amount per tooth after first} = \frac{34}{17} = 2 \, \text{dollars} \]
</reasoning>
<answer>
The tooth fairy left Grant $2 per tooth after his first tooth, assuming equal amounts were exchanged for each of the subsequent teeth.
</answer>
Extracted:
The tooth fairy left Grant $2 per tooth after his first tooth, assuming equal amounts were exchanged for each of the subsequent teeth.
-------------------- Question:
If Billy rode his bike 17 times, John rode his bike twice as many times, and their mother rode her bike 10 times more than John, how many times did they ride their bikes in total?
Answer:
95
Response:
<reasoning>
To solve this problem, first, we determine how many times John rode his bike. Since John rode his bike twice as many times as Billy, and Billy rode his bike 17 times, John rode his bike:
\[ 17 \times 2 = 34 \text{ times.} \]

Next, we find out how many times their mother rode her bike. According to the information, their mother rode her bike 10 times more than John. Since John rode his bike 34 times, the number of times their mother rode her bike would be:
\[ 34 \times 10 = 340 \text{ times.} \]

The total number of times they all rode their bikes can be calculated by adding the counts of Billy, John, and their mother:
\[ 17 \text{ (Billy)} + 34 \text{ (John)} + 340 \text{ (mother)} = 391. \]

</reasoning>
<answer>
391
</answer>
Extracted:
391
-------------------- Question:
Marcus had 18 pebbles. He skipped half of them across the lake, but Freddy gave him another 30 pebbles. How many pebbles does Marcus have now?
Answer:
39
Response:
<reasoning>
First, let's find out how many pebbles Marcus had after skipping half of them. Marcus originally had ��碌18' pebbles. Half of 18 is 9, so Marcus skipped 9 pebbles. Therefore, he had 18 - 9 = 9 pebbles left. Freddy then gave him 30 more pebbles, so Marcus now has 9 + 30 = 39 pebbles.
</reasoning>
<answer>
39
</answer>
Extracted:
39
-------------------- Question:
Jordan noticed that there are 2 cars in his driveway that each have 4 wheels.  There are 2 bikes and a trash can that each have 2 wheels.  There is also a tricycle and a pair of old roller skates.  How many wheels are there?
Answer:
25
Response:
<reasoning>
Jordan has counted the wheels from cars, bikes, a trash can, a tricycle, and roller skates.

- From the 2 cars, there are 2 cars * 4 wheels per car = 8 wheels.
- From the 2 bikes, there are 2 bikes * 2 wheels per bike = 4 wheels.
- From the trash can, there are 1 trash can * 2 wheels = 2 wheels.
- From the tricycle, there is 1 tricycle * 3 wheels = 3 wheels.
- From the roller skates (pair of skates with 2 sets of 4 wheels each), there are 1 pair * (2 sets * 4 wheels) = 8 wheels.
Adding all of this together gives us the total number of wheels.
</reasoning>
<answer>
8 + 4 + 2 + 3 + 8 = 25
</answer>
Extracted:
8 + 4 + 2 + 3 + 8 = 25
-------------------- Question:
Mrs. Wilsborough saved $500 to buy concert tickets for her family. She bought 2 VIP tickets at $100 each and 3 regular tickets at $50 each. How much of her savings does Mrs. Wilsborough have after she buys the tickets?
Answer:
150
Response:
<reasoning>
Mrs. Wilsborough's total savings are $500. She buys 2 VIP tickets for $100 each, which total $2 \times 100 = $200. She also buys 3 regular tickets for $50 each, which total $3 \times 50 = $150. So, the total amount spent on tickets is $200 + $150 = $350. Her savings after buying the tickets is her remaining savings, which is $500 - $350 = $150.
</reasoning>
<answer>
Mrs. Wilsborough has $150 left from her savings after buying the tickets.
</answer>
Extracted:
Mrs. Wilsborough has $150 left from her savings after buying the tickets.
-------------------- Question:
Scott runs 3 miles every Monday through Wednesday. Then he runs twice as far he ran on Monday every Thursday and Friday. How many miles will he run in a month with 4 weeks?
Answer:
84
Response:
<reasoning>
To determine how many miles Scott will run in a month with 4 weeks, we first need to calculate his weekly mileage.

From the problem, Scott runs 3 miles every Monday through Wednesday, which is a total of 3 * 3 = 9 miles for those three days.

From Thursday to Friday, he runs twice as far as he ran on Monday. Since he ran 3 miles on Monday, he will run 2 * 3 = 6 miles on Thursday and Friday combined.

Hence, his weekly total is 9 miles (Monday through Wednesday) + 6 miles (Thursday and Friday) = 15 miles per week.

To find out how many miles he runs over 4 weeks, we multiply the weekly mileage by the number of weeks: 15 * 4 = 60 miles.

</reasoning>
<answer>
Scott will run 60 miles in a month with 4 weeks.
</answer>
Extracted:
Scott will run 60 miles in a month with 4 weeks.
-------------------- Question:
Lard decides to share a pizza with his friend Jelly.  He takes a whole, uncut pepperoni pizza and cuts it in half.  He then cuts these halves in half and gives one of the slices to Jelly.  Assuming the pizza started with 40 evenly spread slices of pepperoni, how many slices of it are on the slice Lard gives Jelly if 1 of them falls off the slice when Lard picks it up?
Answer:
9
Response:
<reasoning>
Lard starts with a whole pizza that, after being cut into slices, would have a total of 40 pepperoni slices. He cuts the pizza in half, which gives him 2 slices. Each of these halves is then cut in half again, making a total of 4 slices. Lard gives one of these 4 slices to Jelly but loses one of the pepperoni slices when he picks it up. If we assume that initially all slices of pepperoni are evenly spread and the loss of 1 slice happens independently from the initial distribution, then every slice, including the one Lard gives Jelly, has 40 / 4 = 10 slices of pepperoni. Since after Lard picks it up 1 of them falls off, the remaining slices of pepperoni on the slice he gives Jelly are 10 - 1 = 9 slices.
</reasoning>
<answer>
9
</answer>
Extracted:
9
-------------------- Question:
A crate can hold 20 kilograms of tomatoes. Tommy has 3 crates which he bought for $330. He wants to sell the tomatoes for $6 per 1 kilogram but 3 kilograms of tomatoes were rotten. How much will be Tommy's profit from selling those tomatoes?
Answer:
12
Response:
<reasoning>
Let's break down the problem step by step:

1. **Calculate the total weight Tommy has:** Since a crate can hold 20 kilograms and Tommy has 3 crates, the total weight would be:
\[ 20 \text{ kg/crate} \times 3 \text{ crates} = 60 \text{ kg} \]

2. **Subtract the rotten tomatoes:** 3 kilograms were rotten, so Tommy can only sell:
\[ 60 \text{ kg} - 3 \text{ kg} = 57 \text{ kg} \]

3. **Determine the revenue from selling the tomatoes:** Tommy sells the tomatoes at $6 per kilogram:
\[ 57 \text{ kg} \times \$6/\text{kg} = \$342 \]

4. **Calculate the cost of the crates:** Tommy bought the 3 crates for $330.

5. **Compute the profit:** The profit is calculated by subtracting the total cost from the total revenue:
\[ \$342 - \$330 = \$12 \]

Therefore, Tommy's profit from selling the tomatoes would be $12.
</reasoning>
<answer>
$12
</answer>
Extracted:
$12
-------------------- Question:
Gwendolyn can read 200 sentences of a book in 1 hour. She just brought a book from the library, having 20 paragraphs per page. What's the total time Gwendolyn will take to read the book if each paragraph has 10 sentences and the book has 50 pages?
Answer:
50
Response:
<reasoning>
To find out how long it will take Gwendolyn to read the entire book, we first need to determine the total number of paragraphs, and then calculate the total number of sentences. We then use her reading speed to determine the time.

Given that the book has 50 pages and each page has 20 paragraphs, the total number of paragraphs in the book is:
\[ 50 \text{ pages} \times 20 \text{ paragraphs/page} = 1000 \text{ paragraphs} \]

Each paragraph contains 10 sentences, so the total number of sentences in the book is:
\[ 1000 \text{ paragraphs} \times 10 \text{ sentences/paragraph} = 10000 \text{ sentences} \]

Gwendolyn can read 200 sentences in 1 hour. So, for 10000 sentences, the time required would be:
\[ \frac{10000 \text{ sentences}}{200 \text{ sentences/hour}} = 50 \text{ hours} \]
</reasoning>
<answer>
Gwendolyn will take 50 hours to read the entire book.
</answer>
Extracted:
Gwendolyn will take 50 hours to read the entire book.
-------------------- Question:
On a 16 GB (gigabyte) capacity USB drive, 50% is already busy. Calculate the number of gigabytes still available.
Answer:
8
Response:
<reasoning>
To find the number of gigabytes still available on a 乱16 GB USB drive that has 50% occupied, we first determine the amount of used space.
- Total capacity = 16 GB
- 50% of 16 GB occupied = 0.5 * 16 GB = 8 GB
- So, the usage is 8 GB.
- To find the remaining space, we subtract the used space from the total capacity: 16 GB - 8 GB = 8 GB
</reasoning>
<answer>
The number of gigabytes still available on the USB drive is 8 GB.
</answer>
Extracted:
The number of gigabytes still available on the USB drive is 8 GB.
-------------------- Question:
Belle eats 4 dog biscuits and 2 rawhide bones every evening. If each rawhide bone is $1, and each dog biscuit is $0.25, then how much does it cost, in dollars, to feed Belle these treats for a week?
Answer:
21
Response:
<reasoning>
To determine the total cost of feeding Belle her treats for a week, we first calculate the daily cost of her food and then multiply it by 7 (since there are 7 days in a week). Belle eats 4 dog biscuits and 2 rawhide bones each evening. The cost per day for her biscuits is \(4 \times \$0.25 = \$1\), and the cost per day for her rawhide bones is \(2 \times \$1 = \$2\). Adding these up, the daily cost is \$1 + \$2 = \$3. To find the weekly cost, we multiply the daily cost by 7: \(3 \times 7 = \$21\).

</reasoning>
<answer>
The cost to feed Belle her treats for a week is $21.
</answer>
Extracted:
The cost to feed Belle her treats for a week is $21.
-------------------- Question:
Rebecca drinks half a bottle of soda a day. She bought three 6-packs of sodas the last time she was at the store. How many bottles of soda will she have left after four weeks?
Answer:
4
Response:
<reasoning>
To solve this problem, we need to perform a few steps to determine how many bottles of soda Rebecca has left after four weeks.

1. First, we calculate the total number of soda bottles Rebecca bought:
   - Three 6-packs of sodas mean \(3 \times 6 = 18\) bottles of soda.

2. We then calculate the total number of soda bottles Rebecca drinks in one day:
   - Rebecca drinks half a bottle of soda each day.

3. Therefore, the total number of soda bottles Rebecca drinks in one week (which is 7 days) is:
   - \(18 \div 12 = 1.5\) bottles/day × 7 days = \(1.5 \times 7 = 10.5\) bottles/week.

4. For four weeks, the total number of soda bottles Rebecca will drink is:
   - \(10.5 \text{ bottles/week} \times 4 = 42 \text{ bottles}\).

5. Finally, we subtract the number of bottles she drank from the total she bought to find out how many bottles are left:
   - \(18 \text{ bottles} - 42 \text{ bottles} = -24 \text{ bottles}\).

However, there's an error here because the number of bottles Rebecca has left can't be negative. The result indicates that Rebecca will not have enough bottles to last for four weeks. In fact, at this point, she would be short by 24 bottles. However, the question's goal with this setup implies we need to correct for the logical mistake, which means understanding the consumption rate per week.


TrainOutput(global_step=100, training_loss=0.00013512650603869858, metrics={'train_runtime': 4997.8909, 'train_samples_per_second': 0.12, 'train_steps_per_second': 0.02, 'total_flos': 0.0, 'train_loss': 0.00013512650603869858})

<a name="Inference"></a>
### Inference
Try inference before adding lora

In [10]:
text = tokenizer.apply_chat_template([
    {"role" : "user", "content" : "How many r's are in strawberry?"},
], tokenize = False, add_generation_prompt = True)

# from vllm import SamplingParams
# sampling_params = SamplingParams(
#     temperature = 0.8,
#     top_p = 0.95,
#     max_tokens = 1024,
# )
output = model.generate(
    tokenizer(text, return_tensors="pt").input_ids.to(model.device),
    temperature = 0.8,
    top_p = 0.95,
    max_new_tokens = 1024,
    # lora_request = None, # This is for vLLM, not needed for transformers generate
)[0]

output = tokenizer.decode(output, skip_special_tokens=True)

output

'system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.\nuser\nHow many r\'s are in strawberry?\nassistant\nThere are no letters \'r\' in the word "strawberry".'

And now with the LoRA we just trained with GRPO - we first save the LoRA first!

In [14]:
model.save_pretrained("grpo_saved_lora")

Now we load the LoRA and test:

In [17]:
text = tokenizer.apply_chat_template([
    {"role" : "system", "content" : SYSTEM_PROMPT},
    {"role" : "user", "content" : "মারির কাছে ৩টা আপেল আছে। সে আরো ২টা কিনলো। মোট কত আপেল??"},
], tokenize = False, add_generation_prompt = True)

# from vllm import SamplingParams # No longer needed
# sampling_params = SamplingParams(
#     temperature = 0.8,
#     top_p = 0.95,
#     max_tokens = 1024,
# ) # No longer needed

output = model.generate(
    tokenizer(text, return_tensors="pt").input_ids.to(model.device),
    temperature = 0.8, # Pass parameters directly
    top_p = 0.95, # Pass parameters directly
    max_new_tokens = 1024, # Use max_new_tokens instead of max_tokens
)[0]

output = tokenizer.decode(output, skip_special_tokens=True)

output

'system\n\nRespond in the following format:\n<reasoning>\n...\n</reasoning>\n<answer>\n...\n</answer>\n\nuser\nমারির কাছে ৩টা আপেল আছে। সে আরো ২টা কিনলো। মোট কত আপেল??\nassistant\n<reasoning>\nমারি মুখে থাকা আপেলগুলি ওকে বর্ণনা দিয乱了, তার নতুন কিনা আপেলগুলিও মুখে থাকা আপেলগুলিকে মিশিয়ে গিয়ে হিসাব রাখতে হবে। মারির মুখে থাকা আপেলগুলিতে ৩টা আছে এবং তার নতুন কিনা ২টা আছে, যা মারির কাছে পৌঝা হয়েছে। যদিও মারির কাছে আপেল আছে, কিনা বা আছে না চিহ্নিত করা নেই অন্যথায় তার মোট আপেল জীবিকা হিসাব রাখতে লজিকালভাবে এই টেক্স্ট ব্যাখ্যা করা যায় না। তাই মোট আপেল সংখ্যাটি প্রস্তাব রাখতে পারেন না।\n</reasoning>\n<answer>\nএই টেক্স্ট ব্যাখ্যায় মারির মোট আপেল সংখ্যা প্রকাশ করা যায় নেই। মারি মুখে থাকা আপেলগুলিকে পরে আরও নতুন আপেলগুলি পরিষ্কার করে ধরা হতে হবে। বর্ণনা নেই, নতুন আপেলগুলি পুনরাবৃত্তির জন্য আমার জন্য কোনও সূত্রায়মান উত্তর পাওয়া যায় নেই।\n</answer>'

In [18]:
print(output)

system

Respond in the following format:
<reasoning>
...
</reasoning>
<answer>
...
</answer>

user
মারির কাছে ৩টা আপেল আছে। সে আরো ২টা কিনলো। মোট কত আপেল??
assistant
<reasoning>
মারি মুখে থাকা আপেলগুলি ওকে বর্ণনা দিয乱了, তার নতুন কিনা আপেলগুলিও মুখে থাকা আপেলগুলিকে মিশিয়ে গিয়ে হিসাব রাখতে হবে। মারির মুখে থাকা আপেলগুলিতে ৩টা আছে এবং তার নতুন কিনা ২টা আছে, যা মারির কাছে পৌঝা হয়েছে। যদিও মারির কাছে আপেল আছে, কিনা বা আছে না চিহ্নিত করা নেই অন্যথায় তার মোট আপেল জীবিকা হিসাব রাখতে লজিকালভাবে এই টেক্স্ট ব্যাখ্যা করা যায় না। তাই মোট আপেল সংখ্যাটি প্রস্তাব রাখতে পারেন না।
</reasoning>
<answer>
এই টেক্স্ট ব্যাখ্যায় মারির মোট আপেল সংখ্যা প্রকাশ করা যায় নেই। মারি মুখে থাকা আপেলগুলিকে পরে আরও নতুন আপেলগুলি পরিষ্কার করে ধরা হতে হবে। বর্ণনা নেই, নতুন আপেলগুলি পুনরাবৃত্তির জন্য আমার জন্য কোনও সূত্রায়মান উত্তর পাওয়া যায় নেই।
</answer>

## Saving

### Save lora adapter

This is both useful for inference and if you want to load the model again

In [22]:
model.push_to_hub(
    "shalhamucha/Qwen2.5-3B-Instruct-Reasoning-for-math",
    tokenizer,
    token = userdata.get('HF_ACCESS_TOKEN')
)

README.md:   0%|          | 0.00/612 [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          |  546kB /  240MB

Saved model to https://huggingface.co/shalhamucha/Qwen2.5-3B-Instruct-Reasoning-for-math

### Merge model with lora weights and save to gguf

You can then do inference locally with Ollama or llama.cpp

##### Popular quantization methods

- **q4_k_m**  
  4bit quantization. Low memory. All models you pull with ollama uses this quantization.
- **q8_0**  
  8bit quantization. Medium memory.
- **f16**  
  16 bit quantization. A lot of models are already in 16 bit so then no quantization happens
- **not_quantized**  
  Often same as f16.

In [2]:
from google.colab import userdata

# model.merge_and_unload_lora() # Remove this line
model.push_to_hub_gguf(
    "shalhamucha/Qwen2.5-3B-Reasoning-math-GGUF",
    tokenizer,
    token = userdata.get('HF_ACCESS_TOKEN')
)

NameError: name 'model' is not defined